name: Build Module

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Extract version
        id: version
        run: |
          VERSION=$(grep -m 1 -oP 'v[0-9]+(\.[0-9]+)+' changelog.md)
          if [ -z "$VERSION" ]; then
            echo "No version found in changelog!"
            exit 1
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Zip Module folder
        run: |
          cd Module
          zip -r ../Yurikey-${{ steps.version.outputs.version }}.signed.zip .
          
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.version }}
          name: Yurikey Manager ${{ steps.version.outputs.version }}
          body_path: changelog.md
          files: Yurikey-${{ steps.version.outputs.version }}.signed.zip
        env:
          GITHUB_TOKEN: ${{ github.token }}
